# Generated by Django 4.2.7 on 2023-11-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mst_usrtbl',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
